-- MySQL Script generated by MySQL Workbench
-- Sun Jun  2 13:44:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exercice_bdd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exercice_bdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exercice_bdd` DEFAULT CHARACTER SET latin1 ;
USE `exercice_bdd` ;

-- -----------------------------------------------------
-- Table `exercice_bdd`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercice_bdd`.`articles` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(30) NOT NULL,
  `Texte` TEXT NOT NULL,
  `Résumé` TEXT NOT NULL,
  `Date` DATETIME NOT NULL,
  `Photos` TEXT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `exercice_bdd`.`catégorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercice_bdd`.`catégorie` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(25) NOT NULL,
  `Description` TEXT NOT NULL,
  `articles_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `articles_ID`),
  INDEX `fk_catégorie_articles1_idx` (`articles_ID` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `exercice_bdd`.`administrateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercice_bdd`.`administrateurs` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Pseudo` VARCHAR(25) NOT NULL,
  `Mail` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(50) NOT NULL,
  `catégorie_ID` INT(11) NOT NULL,
  `catégorie_articles_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `catégorie_ID`, `catégorie_articles_ID`),
  INDEX `fk_administrateurs_catégorie1_idx` (`catégorie_ID` ASC, `catégorie_articles_ID` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `exercice_bdd`.`comment_anonyme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercice_bdd`.`comment_anonyme` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Comment` TEXT NOT NULL,
  `Date` DATETIME NOT NULL,
  `articles_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `articles_ID`),
  INDEX `fk_comment_anonyme_articles1_idx` (`articles_ID` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `exercice_bdd`.`comment_utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercice_bdd`.`comment_utilisateur` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Pseudo` VARCHAR(25) NOT NULL,
  `Commentaire` TEXT NOT NULL,
  `Date` DATETIME NOT NULL,
  `articles_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `articles_ID`),
  INDEX `fk_comment_utilisateur_articles1_idx` (`articles_ID` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `exercice_bdd`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercice_bdd`.`utilisateurs` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Pseudo` VARCHAR(25) NOT NULL,
  `Mail` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(15) NOT NULL,
  `comment_utilisateur_ID` INT(11) NOT NULL,
  `articles_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `comment_utilisateur_ID`, `articles_ID`),
  INDEX `fk_utilisateurs_comment_utilisateur1_idx` (`comment_utilisateur_ID` ASC) VISIBLE,
  INDEX `fk_utilisateurs_articles1_idx` (`articles_ID` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
